events {}

http {

    upstream flask_backend {
        server host.containers.internal:8081;
        server host.containers.internal:8082;
        server host.containers.internal:5003;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flask_backend;
        }
    }

}